export enum SyntaxKind {
    UnknownSyntax = 1000,
    UnknownStatement = 1001,
    UnknownExpression = 1002,
    Value = 1003,
    BitDataType = 1004,
    BooleanDataType = 1005,
    IntegerDataType = 1006,
    DecimalDataType = 1007,
    RealDataType = 1008,
    JsonDataType = 1009,
    CharacterDataType = 1010,
    TextDataType = 1011,
    BinaryDataType = 1012,
    BlobDataType = 1013,
    DateTimeDataType = 1014,
    YearDataType = 1015,
    DateDataType = 1016,
    TimeDataType = 1017,
    TimestampDataType = 1018,
    GeometryDataType = 1019,
    GeometryCollectionDataType = 1020,
    EnumDataType = 1021,
    SetDataType = 1022,
    UnionDataType = 1023,
    UnknownDataType = 1024,
    SourceFileLite = 1025,
    SourceFile = 1026,
    Program = 1027,
    DelimiterStatement = 1028,
    CurrentTimestamp = 1029,
    DefaultCollation = 1030,
    DefaultCharacterSet = 1031,
    FieldLength = 1032,
    Precision = 1033,
    Interval = 1034,
    SizeNumber = 1035,
    CreateSchemaStatement = 1036,
    CreateSchemaOptionList = 1037,
    CreateTableStatement = 1038,
    ColumnDefinition = 1039,
    GeneratedDefinition = 1040,
    ForeignKeyReferenceDefinition = 1041,
    IndexDefinition = 1042,
    IndexPart = 1043,
    PrimaryKeyDefinition = 1044,
    ForeignKeyDefinition = 1045,
    CheckDefinition = 1046,
    CreateTableOptions = 1047,
    CreateFunctionStatement = 1048,
    StoredFunctionParameter = 1049,
    StoredFunctionParameterList = 1050,
    StoredProcedureCharacteristics = 1051,
    CreateProcedureStatement = 1052,
    StoredProcedureParameter = 1053,
    StoredProcedureParameterList = 1054,
    CreateTriggerStatement = 1055,
    TriggerOrder = 1056,
    CreateEventStatement = 1057,
    ExecuteAtSchedule = 1058,
    IntervalSchedule = 1059,
    CreateUserDefinedFunctionStatement = 1060,
    CreateViewStatement = 1061,
    CreateUserStatement = 1062,
    GrantUser = 1063,
    GrantUserList = 1064,
    RequiredEncryptedConnectionOptions = 1065,
    RateLimitOptions = 1066,
    AccountLockAndPasswordExpiryOptions = 1067,
    CreateLogFileGroupStatement = 1068,
    CreateLogFileGroupOptions = 1069,
    CreateLogFileGroupAddRedoFile = 1070,
    CreateLogFileGroupAddUndoFile = 1071,
    CreateTablespaceStatement = 1072,
    CreateTablespaceOptions = 1073,
    HashPartition = 1074,
    KeyPartition = 1075,
    ListPartition = 1076,
    RangePartition = 1077,
    HashSubPartition = 1078,
    KeySubPartition = 1079,
    ListPartitionDefinition = 1080,
    RangePartitionDefinition = 1081,
    SubPartitionDefinition = 1082,
    PartitionDefinitionOptions = 1083,
    SetStatement = 1084,
    Assignment = 1085,
    SelectStatement = 1086,
    Select = 1087,
    SelectOptions = 1088,
    SelectItem = 1089,
    AsteriskSelectItem = 1090,
    TableAsteriskSelectItem = 1091,
    IntoOption = 1092,
    OdbcTableReference = 1093,
    NamedTableFactor = 1094,
    IndexHintDefinition = 1095,
    DerivedTableFactor = 1096,
    FromClause = 1097,
    Join = 1098,
    JoinSpecificationUsing = 1099,
    JoinSpecificationOn = 1100,
    WhereClause = 1101,
    GroupByClause = 1102,
    GroupingExpr = 1103,
    HavingClause = 1104,
    OrderByClause = 1105,
    OrderExpr = 1106,
    Limit = 1107,
    ProcedureAnalyseClause = 1108,
    IntoClause = 1109,
    IntoDestinationDumpFile = 1110,
    IntoDestinationOutFile = 1111,
    IntoDestinationVariableList = 1112,
    FieldTerminatorOptions = 1113,
    LineTerminatorOptions = 1114,
    Union = 1115,
    UnionOrderLimit = 1116,
    ReturnStatement = 1117,
    LabelStatement = 1118,
    BlockStatement = 1119,
    LoopStatement = 1120,
    WhileStatement = 1121,
    RepeatStatement = 1122,
    IfStatement = 1123,
    ElseIf = 1124,
    ElseBranch = 1125,
    SimpleCaseStatement = 1126,
    SimpleWhen = 1127,
    SimpleWhenList = 1128,
    SearchedCaseStatement = 1129,
    SearchedWhen = 1130,
    SearchedWhenList = 1131,
    LeaveStatement = 1132,
    IterateStatement = 1133,
    OpenStatement = 1134,
    CloseStatement = 1135,
    FetchStatement = 1136,
    DeclareFunctionStatement = 1137,
    DeclareFunctionParameter = 1138,
    CreateMacroStatement = 1139,
    Identifier = 1140,
    UserVariableIdentifier = 1141,
    SystemVariableIdentifier = 1142,
    TableIdentifier = 1143,
    ColumnIdentifier = 1144,
    FunctionIdentifier = 1145,
    MacroIdentifier = 1146,
    StoredFunctionIdentifier = 1147,
    StoredProcedureIdentifier = 1148,
    AccountIdentifier = 1149,
    TriggerIdentifier = 1150,
    EventIdentifier = 1151,
    ParenthesizedExpression = 1152,
    BinaryExpression = 1153,
    UnaryExpression = 1154,
    ColumnExpression = 1155,
    FunctionCallExpression = 1156,
    RowExpression = 1157,
    MacroCallExpression = 1158,
    CaseIfExpression = 1159,
    CaseSwitchExpression = 1160,
    CaseBranch = 1161,
    MatchExpression = 1162,
    NullLiteral = 1163,
    BooleanLiteral = 1164,
    StringLiteral = 1165,
    HexLiteral = 1166,
    BitLiteral = 1167,
    IntegerLiteral = 1168,
    DecimalLiteral = 1169,
    RealLiteral = 1170,
    ParamMarker = 1171,
    DataTypeList = 1172,
    DeclareFunctionParameterList = 1173,
    ArgumentList = 1174,
    AssignmentList = 1175,
    CaseBranchList = 1176,
    CreateTableDefinitionList = 1177,
    IdentifierList = 1178,
    IntoOptionVariableList = 1179,
    JoinDefinitionList = 1180,
    SelectItemList = 1181,
    SourceElementList = 1182,
    ColumnIdentifierList = 1183,
    OrderItemList = 1184,
    IndexPartList = 1185,
    StringList = 1186,
    TableIdentifierList = 1187,
    ListPartitionDefinitionList = 1188,
    RangePartitionDefinitionList = 1189,
    ExpressionList = 1190,
    ExpressionListList = 1191,
    SubPartitionDefinitionList = 1192,
    ExpressionOrMaxValueList = 1193,
    OrderExprList = 1194,
    TableReferenceList = 1195,
    IndexHintDefinitionList = 1196,
    KeyUsageList = 1197,
    GroupingExprList = 1198,
    StoredProcedureStatementList = 1199,
    ElseIfList = 1200,
    FetchIdentifierList = 1201,
}

//https://dev.mysql.com/doc/refman/5.7/en/manual-info.html
export const syntaxKinds = [
    "UnknownSyntax",
    "UnknownStatement",
    "UnknownExpression",

    "Value",

    "BitDataType",
    "BooleanDataType",
    "IntegerDataType",
    "DecimalDataType",
    "RealDataType",

    "JsonDataType",

    "CharacterDataType",
    "TextDataType",
    "BinaryDataType",
    "BlobDataType",

    "DateTimeDataType",
    "YearDataType",
    "DateDataType",
    "TimeDataType",
    "TimestampDataType",

    "GeometryDataType",
    "GeometryCollectionDataType",

    "EnumDataType",
    "SetDataType",

    "UnionDataType",
    "UnknownDataType",

    /**
     * Top-Level nodes
     */
    "SourceFileLite",
    "SourceFile",
    "Program",

    /**
     * The custom delimiter is used for the MySQL
     * `DELIMITER` command.
     */
    "DelimiterStatement",

    /**
     * Misc
     */
    "CurrentTimestamp",
    "DefaultCollation",
    "DefaultCharacterSet",
    "FieldLength",
    "Precision",
    "Interval",
    "SizeNumber",

    /**
     * Statements
     */
    "CreateSchemaStatement",
    "CreateSchemaOptionList",

    "CreateTableStatement",
    "ColumnDefinition",
    "GeneratedDefinition",
    "ForeignKeyReferenceDefinition",
    "IndexDefinition",
    "IndexPart",
    "PrimaryKeyDefinition",
    "ForeignKeyDefinition",
    "CheckDefinition",
    "CreateTableOptions",

    "CreateFunctionStatement",
    "StoredFunctionParameter",
    "StoredFunctionParameterList",
    "StoredProcedureCharacteristics",
    "CreateProcedureStatement",
    "StoredProcedureParameter",
    "StoredProcedureParameterList",
    "CreateTriggerStatement",
    "TriggerOrder",
    "CreateEventStatement",
    "ExecuteAtSchedule",
    "IntervalSchedule",
    "CreateUserDefinedFunctionStatement",
    "CreateViewStatement",
    "CreateUserStatement",
    "GrantUser",
    "GrantUserList",
    "RequiredEncryptedConnectionOptions",
    "RateLimitOptions",
    "AccountLockAndPasswordExpiryOptions",
    "CreateLogFileGroupStatement",
    "CreateLogFileGroupOptions",
    "CreateLogFileGroupAddRedoFile",
    "CreateLogFileGroupAddUndoFile",
    "CreateTablespaceStatement",
    "CreateTablespaceOptions",

    "HashPartition",
    "KeyPartition",
    "ListPartition",
    "RangePartition",

    "HashSubPartition",
    "KeySubPartition",

    "ListPartitionDefinition",
    "RangePartitionDefinition",

    "SubPartitionDefinition",

    "PartitionDefinitionOptions",

    "SetStatement",
    "Assignment",

    "SelectStatement",
    "Select",
    "SelectOptions",
    "SelectItem",
    "AsteriskSelectItem",
    "TableAsteriskSelectItem",
    "IntoOption",
    "OdbcTableReference",
    "NamedTableFactor",
    "IndexHintDefinition",
    "DerivedTableFactor",
    "FromClause",
    "Join",
    "JoinSpecificationUsing",
    "JoinSpecificationOn",
    "WhereClause",
    "GroupByClause",
    "GroupingExpr",
    "HavingClause",
    "OrderByClause",
    "OrderExpr",
    "Limit",
    "ProcedureAnalyseClause",
    "IntoClause",
    "IntoDestinationDumpFile",
    "IntoDestinationOutFile",
    "IntoDestinationVariableList",
    "FieldTerminatorOptions",
    "LineTerminatorOptions",
    "Union",
    "UnionOrderLimit",

    /**
     * Stored procedure statements
     */
    "ReturnStatement",
    "LabelStatement",
    "BlockStatement",
    "LoopStatement",
    "WhileStatement",
    "RepeatStatement",
    "IfStatement",
    "ElseIf",
    "ElseBranch",
    "SimpleCaseStatement",
    "SimpleWhen",
    "SimpleWhenList",
    "SearchedCaseStatement",
    "SearchedWhen",
    "SearchedWhenList",
    "LeaveStatement",
    "IterateStatement",
    "OpenStatement",
    "CloseStatement",
    "FetchStatement",

    /**
     * Custom statements
     */
    "DeclareFunctionStatement",
    "DeclareFunctionParameter",

    "CreateMacroStatement",

    /**
     * May be escaped or unescaped with backticks, or double quotes
     */
    "Identifier",
    /**
     * Starts with one ampersand.
     */
    "UserVariableIdentifier",
    /**
     * Starts with two ampersands.
     */
    "SystemVariableIdentifier",
    "TableIdentifier",
    "ColumnIdentifier",
    "FunctionIdentifier",
    "MacroIdentifier",
    "StoredFunctionIdentifier",
    "StoredProcedureIdentifier",
    "AccountIdentifier",
    "TriggerIdentifier",
    "EventIdentifier",

    /**
     * Expression
     */
    "ParenthesizedExpression",
    "BinaryExpression",
    "UnaryExpression",
    "ColumnExpression",
    "FunctionCallExpression",
    "RowExpression",
    "MacroCallExpression",
    "CaseIfExpression",
    "CaseSwitchExpression",
    "CaseBranch",
    "MatchExpression",

    "NullLiteral",
    "BooleanLiteral",
    "StringLiteral",
    "HexLiteral",
    "BitLiteral",
    "IntegerLiteral",
    "DecimalLiteral",
    "RealLiteral",
    "ParamMarker",

    "DataTypeList",
    "DeclareFunctionParameterList",
    "ArgumentList",
    "AssignmentList",
    "CaseBranchList",
    "CreateTableDefinitionList",
    "IdentifierList",
    "IntoOptionVariableList",
    "JoinDefinitionList",
    "SelectItemList",
    "SourceElementList",
    "ColumnIdentifierList",
    "OrderItemList",
    "IndexPartList",
    "StringList",
    "TableIdentifierList",
    "ListPartitionDefinitionList",
    "RangePartitionDefinitionList",
    "ExpressionList",
    "ExpressionListList",
    "SubPartitionDefinitionList",
    "ExpressionOrMaxValueList",
    "OrderExprList",
    "TableReferenceList",
    "IndexHintDefinitionList",
    "KeyUsageList",
    "GroupingExprList",
    "StoredProcedureStatementList",
    "ElseIfList",
    "FetchIdentifierList",
] as const;

