export enum SyntaxKind {
    UnknownSyntax = 1000,
    UnknownStatement = 1001,
    UnknownExpression = 1002,
    Value = 1003,
    BitDataType = 1004,
    BooleanDataType = 1005,
    IntegerDataType = 1006,
    DecimalDataType = 1007,
    RealDataType = 1008,
    JsonDataType = 1009,
    CharacterDataType = 1010,
    TextDataType = 1011,
    BinaryDataType = 1012,
    BlobDataType = 1013,
    DateTimeDataType = 1014,
    YearDataType = 1015,
    DateDataType = 1016,
    TimeDataType = 1017,
    TimestampDataType = 1018,
    GeometryDataType = 1019,
    GeometryCollectionDataType = 1020,
    EnumDataType = 1021,
    SetDataType = 1022,
    UnionDataType = 1023,
    UnknownDataType = 1024,
    SourceFileLite = 1025,
    SourceFile = 1026,
    Program = 1027,
    DelimiterStatement = 1028,
    CurrentTimestamp = 1029,
    DefaultCollation = 1030,
    DefaultCharacterSet = 1031,
    FieldLength = 1032,
    Precision = 1033,
    Interval = 1034,
    SizeNumber = 1035,
    CreateSchemaStatement = 1036,
    CreateSchemaOptionList = 1037,
    CreateTableStatement = 1038,
    ColumnDefinition = 1039,
    GeneratedDefinition = 1040,
    ForeignKeyReferenceDefinition = 1041,
    IndexDefinition = 1042,
    IndexPart = 1043,
    PrimaryKeyDefinition = 1044,
    ForeignKeyDefinition = 1045,
    CheckDefinition = 1046,
    CreateTableOptions = 1047,
    CreateTableSelectStatement = 1048,
    CreateTableSelect = 1049,
    CreateTableLikeStatement = 1050,
    CreateFunctionStatement = 1051,
    StoredFunctionParameter = 1052,
    StoredFunctionParameterList = 1053,
    StoredProcedureCharacteristics = 1054,
    CreateProcedureStatement = 1055,
    StoredProcedureParameter = 1056,
    StoredProcedureParameterList = 1057,
    CreateTriggerStatement = 1058,
    TriggerOrder = 1059,
    CreateEventStatement = 1060,
    ExecuteAtSchedule = 1061,
    IntervalSchedule = 1062,
    CreateUserDefinedFunctionStatement = 1063,
    CreateViewStatement = 1064,
    CreateUserStatement = 1065,
    GrantUser = 1066,
    GrantUserList = 1067,
    RequiredEncryptedConnectionOptions = 1068,
    RateLimitOptions = 1069,
    AccountLockAndPasswordExpiryOptions = 1070,
    CreateLogFileGroupStatement = 1071,
    CreateLogFileGroupOptions = 1072,
    CreateLogFileGroupAddRedoFile = 1073,
    CreateLogFileGroupAddUndoFile = 1074,
    CreateTablespaceStatement = 1075,
    CreateTablespaceOptions = 1076,
    CreateServerStatement = 1077,
    CreateServerOptions = 1078,
    CreateIndexStatement = 1079,
    AlterTableLockAndAlgorithmOptions = 1080,
    AlterTableStatement = 1081,
    AlterTableStandaloneStatement = 1082,
    AlterTableModifiers = 1083,
    AlterTableLock = 1084,
    AlterTableAlgorithm = 1085,
    AlterTableValidation = 1086,
    AlterTableItemOrModifierList = 1087,
    AlterTableAddColumn = 1088,
    AlterTableAddCreateTableDefinitionList = 1089,
    AlterTableChangeColumn = 1090,
    AlterTableModifyColumn = 1091,
    AlterTableDropColumn = 1092,
    AlterTableDropForeignKey = 1093,
    AlterTableDropPrimaryKey = 1094,
    AlterTableDropIndex = 1095,
    AlterTableDisableKeys = 1096,
    AlterTableEnableKeys = 1097,
    AlterTableAlterColumnSetDefault = 1098,
    AlterTableAlterColumnDropDefault = 1099,
    AlterTableRenameTable = 1100,
    AlterTableRenameIndex = 1101,
    AlterTableConvertToCharacterSet = 1102,
    AlterTableForce = 1103,
    AlterTableUpgradePartitioning = 1104,
    AlterTableOrderBy = 1105,
    AlterTableOrderExprList = 1106,
    AlterTableOrderExpr = 1107,
    AlterSchemaStatement = 1108,
    HashPartition = 1109,
    KeyPartition = 1110,
    ListPartition = 1111,
    RangePartition = 1112,
    HashSubPartition = 1113,
    KeySubPartition = 1114,
    ListPartitionDefinition = 1115,
    RangePartitionDefinition = 1116,
    SubPartitionDefinition = 1117,
    PartitionDefinitionOptions = 1118,
    SetStatement = 1119,
    Assignment = 1120,
    SelectStatement = 1121,
    Select = 1122,
    SelectOptions = 1123,
    SelectItem = 1124,
    AsteriskSelectItem = 1125,
    TableAsteriskSelectItem = 1126,
    IntoOption = 1127,
    OdbcTableReference = 1128,
    NamedTableFactor = 1129,
    IndexHintDefinition = 1130,
    DerivedTableFactor = 1131,
    FromClause = 1132,
    Join = 1133,
    JoinSpecificationUsing = 1134,
    JoinSpecificationOn = 1135,
    WhereClause = 1136,
    GroupByClause = 1137,
    GroupingExpr = 1138,
    HavingClause = 1139,
    OrderByClause = 1140,
    OrderExpr = 1141,
    Limit = 1142,
    ProcedureAnalyseClause = 1143,
    IntoClause = 1144,
    IntoDestinationDumpFile = 1145,
    IntoDestinationOutFile = 1146,
    IntoDestinationVariableList = 1147,
    FieldTerminatorOptions = 1148,
    LineTerminatorOptions = 1149,
    Union = 1150,
    UnionOrderLimit = 1151,
    ReturnStatement = 1152,
    LabelStatement = 1153,
    BlockStatement = 1154,
    LoopStatement = 1155,
    WhileStatement = 1156,
    RepeatStatement = 1157,
    IfStatement = 1158,
    ElseIf = 1159,
    ElseBranch = 1160,
    SimpleCaseStatement = 1161,
    SimpleWhen = 1162,
    SimpleWhenList = 1163,
    SearchedCaseStatement = 1164,
    SearchedWhen = 1165,
    SearchedWhenList = 1166,
    LeaveStatement = 1167,
    IterateStatement = 1168,
    OpenStatement = 1169,
    CloseStatement = 1170,
    FetchStatement = 1171,
    DeclareFunctionStatement = 1172,
    DeclareFunctionParameter = 1173,
    CreateMacroStatement = 1174,
    Identifier = 1175,
    UserVariableIdentifier = 1176,
    SystemVariableIdentifier = 1177,
    TableIdentifier = 1178,
    ColumnIdentifier = 1179,
    FunctionIdentifier = 1180,
    MacroIdentifier = 1181,
    StoredFunctionIdentifier = 1182,
    StoredProcedureIdentifier = 1183,
    AccountIdentifier = 1184,
    TriggerIdentifier = 1185,
    EventIdentifier = 1186,
    ParenthesizedExpression = 1187,
    BinaryExpression = 1188,
    UnaryExpression = 1189,
    ColumnExpression = 1190,
    FunctionCallExpression = 1191,
    RowExpression = 1192,
    MacroCallExpression = 1193,
    CaseIfExpression = 1194,
    CaseSwitchExpression = 1195,
    CaseBranch = 1196,
    MatchExpression = 1197,
    NullLiteral = 1198,
    BooleanLiteral = 1199,
    StringLiteral = 1200,
    HexLiteral = 1201,
    BitLiteral = 1202,
    IntegerLiteral = 1203,
    DecimalLiteral = 1204,
    RealLiteral = 1205,
    ParamMarker = 1206,
    DataTypeList = 1207,
    DeclareFunctionParameterList = 1208,
    ArgumentList = 1209,
    AssignmentList = 1210,
    CaseBranchList = 1211,
    CreateTableDefinitionList = 1212,
    IdentifierList = 1213,
    IntoOptionVariableList = 1214,
    JoinDefinitionList = 1215,
    SelectItemList = 1216,
    SourceElementList = 1217,
    ColumnIdentifierList = 1218,
    OrderItemList = 1219,
    IndexPartList = 1220,
    StringList = 1221,
    TableIdentifierList = 1222,
    ListPartitionDefinitionList = 1223,
    RangePartitionDefinitionList = 1224,
    ExpressionList = 1225,
    ExpressionListList = 1226,
    SubPartitionDefinitionList = 1227,
    ExpressionOrMaxValueList = 1228,
    OrderExprList = 1229,
    TableReferenceList = 1230,
    IndexHintDefinitionList = 1231,
    KeyUsageList = 1232,
    GroupingExprList = 1233,
    StoredProcedureStatementList = 1234,
    ElseIfList = 1235,
    FetchIdentifierList = 1236,
}

//https://dev.mysql.com/doc/refman/5.7/en/manual-info.html
export const syntaxKinds = [
    "UnknownSyntax",
    "UnknownStatement",
    "UnknownExpression",

    "Value",

    "BitDataType",
    "BooleanDataType",
    "IntegerDataType",
    "DecimalDataType",
    "RealDataType",

    "JsonDataType",

    "CharacterDataType",
    "TextDataType",
    "BinaryDataType",
    "BlobDataType",

    "DateTimeDataType",
    "YearDataType",
    "DateDataType",
    "TimeDataType",
    "TimestampDataType",

    "GeometryDataType",
    "GeometryCollectionDataType",

    "EnumDataType",
    "SetDataType",

    "UnionDataType",
    "UnknownDataType",

    /**
     * Top-Level nodes
     */
    "SourceFileLite",
    "SourceFile",
    "Program",

    /**
     * The custom delimiter is used for the MySQL
     * `DELIMITER` command.
     */
    "DelimiterStatement",

    /**
     * Misc
     */
    "CurrentTimestamp",
    "DefaultCollation",
    "DefaultCharacterSet",
    "FieldLength",
    "Precision",
    "Interval",
    "SizeNumber",

    /**
     * Statements
     */
    "CreateSchemaStatement",
    "CreateSchemaOptionList",

    "CreateTableStatement",
    "ColumnDefinition",
    "GeneratedDefinition",
    "ForeignKeyReferenceDefinition",
    "IndexDefinition",
    "IndexPart",
    "PrimaryKeyDefinition",
    "ForeignKeyDefinition",
    "CheckDefinition",
    "CreateTableOptions",

    "CreateTableSelectStatement",
    "CreateTableSelect",

    "CreateTableLikeStatement",

    "CreateFunctionStatement",
    "StoredFunctionParameter",
    "StoredFunctionParameterList",
    "StoredProcedureCharacteristics",
    "CreateProcedureStatement",
    "StoredProcedureParameter",
    "StoredProcedureParameterList",
    "CreateTriggerStatement",
    "TriggerOrder",
    "CreateEventStatement",
    "ExecuteAtSchedule",
    "IntervalSchedule",
    "CreateUserDefinedFunctionStatement",
    "CreateViewStatement",
    "CreateUserStatement",
    "GrantUser",
    "GrantUserList",
    "RequiredEncryptedConnectionOptions",
    "RateLimitOptions",
    "AccountLockAndPasswordExpiryOptions",
    "CreateLogFileGroupStatement",
    "CreateLogFileGroupOptions",
    "CreateLogFileGroupAddRedoFile",
    "CreateLogFileGroupAddUndoFile",
    "CreateTablespaceStatement",
    "CreateTablespaceOptions",
    "CreateServerStatement",
    "CreateServerOptions",
    "CreateIndexStatement",
    "AlterTableLockAndAlgorithmOptions",

    "AlterTableStatement",
    "AlterTableStandaloneStatement",

    "AlterTableModifiers",
    "AlterTableLock",
    "AlterTableAlgorithm",
    "AlterTableValidation",

    "AlterTableItemOrModifierList",

    "AlterTableAddColumn",
    "AlterTableAddCreateTableDefinitionList",
    "AlterTableChangeColumn",
    "AlterTableModifyColumn",
    "AlterTableDropColumn",
    "AlterTableDropForeignKey",
    "AlterTableDropPrimaryKey",
    "AlterTableDropIndex",
    "AlterTableDisableKeys",
    "AlterTableEnableKeys",
    "AlterTableAlterColumnSetDefault",
    "AlterTableAlterColumnDropDefault",
    /**
     * @todo Renaming columns only added in MySQL 8.0
     */
    "AlterTableRenameTable",
    "AlterTableRenameIndex",
    "AlterTableConvertToCharacterSet",
    "AlterTableForce",
    "AlterTableUpgradePartitioning",
    "AlterTableOrderBy",
    "AlterTableOrderExprList",
    "AlterTableOrderExpr",

    "AlterSchemaStatement",

    "HashPartition",
    "KeyPartition",
    "ListPartition",
    "RangePartition",

    "HashSubPartition",
    "KeySubPartition",

    "ListPartitionDefinition",
    "RangePartitionDefinition",

    "SubPartitionDefinition",

    "PartitionDefinitionOptions",

    "SetStatement",
    "Assignment",

    "SelectStatement",
    "Select",
    "SelectOptions",
    "SelectItem",
    "AsteriskSelectItem",
    "TableAsteriskSelectItem",
    "IntoOption",
    "OdbcTableReference",
    "NamedTableFactor",
    "IndexHintDefinition",
    "DerivedTableFactor",
    "FromClause",
    "Join",
    "JoinSpecificationUsing",
    "JoinSpecificationOn",
    "WhereClause",
    "GroupByClause",
    "GroupingExpr",
    "HavingClause",
    "OrderByClause",
    "OrderExpr",
    "Limit",
    "ProcedureAnalyseClause",
    "IntoClause",
    "IntoDestinationDumpFile",
    "IntoDestinationOutFile",
    "IntoDestinationVariableList",
    "FieldTerminatorOptions",
    "LineTerminatorOptions",
    "Union",
    "UnionOrderLimit",

    /**
     * Stored procedure statements
     */
    "ReturnStatement",
    "LabelStatement",
    "BlockStatement",
    "LoopStatement",
    "WhileStatement",
    "RepeatStatement",
    "IfStatement",
    "ElseIf",
    "ElseBranch",
    "SimpleCaseStatement",
    "SimpleWhen",
    "SimpleWhenList",
    "SearchedCaseStatement",
    "SearchedWhen",
    "SearchedWhenList",
    "LeaveStatement",
    "IterateStatement",
    "OpenStatement",
    "CloseStatement",
    "FetchStatement",

    /**
     * Custom statements
     */
    "DeclareFunctionStatement",
    "DeclareFunctionParameter",

    "CreateMacroStatement",

    /**
     * May be escaped or unescaped with backticks, or double quotes
     */
    "Identifier",
    /**
     * Starts with one ampersand.
     */
    "UserVariableIdentifier",
    /**
     * Starts with two ampersands.
     */
    "SystemVariableIdentifier",
    "TableIdentifier",
    "ColumnIdentifier",
    "FunctionIdentifier",
    "MacroIdentifier",
    "StoredFunctionIdentifier",
    "StoredProcedureIdentifier",
    "AccountIdentifier",
    "TriggerIdentifier",
    "EventIdentifier",

    /**
     * Expression
     */
    "ParenthesizedExpression",
    "BinaryExpression",
    "UnaryExpression",
    "ColumnExpression",
    "FunctionCallExpression",
    "RowExpression",
    "MacroCallExpression",
    "CaseIfExpression",
    "CaseSwitchExpression",
    "CaseBranch",
    "MatchExpression",

    "NullLiteral",
    "BooleanLiteral",
    "StringLiteral",
    "HexLiteral",
    "BitLiteral",
    "IntegerLiteral",
    "DecimalLiteral",
    "RealLiteral",
    "ParamMarker",

    "DataTypeList",
    "DeclareFunctionParameterList",
    "ArgumentList",
    "AssignmentList",
    "CaseBranchList",
    "CreateTableDefinitionList",
    "IdentifierList",
    "IntoOptionVariableList",
    "JoinDefinitionList",
    "SelectItemList",
    "SourceElementList",
    "ColumnIdentifierList",
    "OrderItemList",
    "IndexPartList",
    "StringList",
    "TableIdentifierList",
    "ListPartitionDefinitionList",
    "RangePartitionDefinitionList",
    "ExpressionList",
    "ExpressionListList",
    "SubPartitionDefinitionList",
    "ExpressionOrMaxValueList",
    "OrderExprList",
    "TableReferenceList",
    "IndexHintDefinitionList",
    "KeyUsageList",
    "GroupingExprList",
    "StoredProcedureStatementList",
    "ElseIfList",
    "FetchIdentifierList",
] as const;

