
export const characterSet = new Map([
    ["big5", {"characterSet":"big5","description":"Big5 Traditional Chinese","defaultCollation":"big5_chinese_ci","maxLength":2}],
    ["dec8", {"characterSet":"dec8","description":"DEC West European","defaultCollation":"dec8_swedish_ci","maxLength":1}],
    ["cp850", {"characterSet":"cp850","description":"DOS West European","defaultCollation":"cp850_general_ci","maxLength":1}],
    ["hp8", {"characterSet":"hp8","description":"HP West European","defaultCollation":"hp8_english_ci","maxLength":1}],
    ["koi8r", {"characterSet":"koi8r","description":"KOI8-R Relcom Russian","defaultCollation":"koi8r_general_ci","maxLength":1}],
    ["latin1", {"characterSet":"latin1","description":"cp1252 West European","defaultCollation":"latin1_swedish_ci","maxLength":1}],
    ["latin2", {"characterSet":"latin2","description":"ISO 8859-2 Central European","defaultCollation":"latin2_general_ci","maxLength":1}],
    ["swe7", {"characterSet":"swe7","description":"7bit Swedish","defaultCollation":"swe7_swedish_ci","maxLength":1}],
    ["ascii", {"characterSet":"ascii","description":"US ASCII","defaultCollation":"ascii_general_ci","maxLength":1}],
    ["ujis", {"characterSet":"ujis","description":"EUC-JP Japanese","defaultCollation":"ujis_japanese_ci","maxLength":3}],
    ["sjis", {"characterSet":"sjis","description":"Shift-JIS Japanese","defaultCollation":"sjis_japanese_ci","maxLength":2}],
    ["hebrew", {"characterSet":"hebrew","description":"ISO 8859-8 Hebrew","defaultCollation":"hebrew_general_ci","maxLength":1}],
    ["tis620", {"characterSet":"tis620","description":"TIS620 Thai","defaultCollation":"tis620_thai_ci","maxLength":1}],
    ["euckr", {"characterSet":"euckr","description":"EUC-KR Korean","defaultCollation":"euckr_korean_ci","maxLength":2}],
    ["koi8u", {"characterSet":"koi8u","description":"KOI8-U Ukrainian","defaultCollation":"koi8u_general_ci","maxLength":1}],
    ["gb2312", {"characterSet":"gb2312","description":"GB2312 Simplified Chinese","defaultCollation":"gb2312_chinese_ci","maxLength":2}],
    ["greek", {"characterSet":"greek","description":"ISO 8859-7 Greek","defaultCollation":"greek_general_ci","maxLength":1}],
    ["cp1250", {"characterSet":"cp1250","description":"Windows Central European","defaultCollation":"cp1250_general_ci","maxLength":1}],
    ["gbk", {"characterSet":"gbk","description":"GBK Simplified Chinese","defaultCollation":"gbk_chinese_ci","maxLength":2}],
    ["latin5", {"characterSet":"latin5","description":"ISO 8859-9 Turkish","defaultCollation":"latin5_turkish_ci","maxLength":1}],
    ["armscii8", {"characterSet":"armscii8","description":"ARMSCII-8 Armenian","defaultCollation":"armscii8_general_ci","maxLength":1}],
    ["utf8", {"characterSet":"utf8","description":"UTF-8 Unicode","defaultCollation":"utf8_general_ci","maxLength":3}],
    ["ucs2", {"characterSet":"ucs2","description":"UCS-2 Unicode","defaultCollation":"ucs2_general_ci","maxLength":2}],
    ["cp866", {"characterSet":"cp866","description":"DOS Russian","defaultCollation":"cp866_general_ci","maxLength":1}],
    ["keybcs2", {"characterSet":"keybcs2","description":"DOS Kamenicky Czech-Slovak","defaultCollation":"keybcs2_general_ci","maxLength":1}],
    ["macce", {"characterSet":"macce","description":"Mac Central European","defaultCollation":"macce_general_ci","maxLength":1}],
    ["macroman", {"characterSet":"macroman","description":"Mac West European","defaultCollation":"macroman_general_ci","maxLength":1}],
    ["cp852", {"characterSet":"cp852","description":"DOS Central European","defaultCollation":"cp852_general_ci","maxLength":1}],
    ["latin7", {"characterSet":"latin7","description":"ISO 8859-13 Baltic","defaultCollation":"latin7_general_ci","maxLength":1}],
    ["utf8mb4", {"characterSet":"utf8mb4","description":"UTF-8 Unicode","defaultCollation":"utf8mb4_general_ci","maxLength":4}],
    ["cp1251", {"characterSet":"cp1251","description":"Windows Cyrillic","defaultCollation":"cp1251_general_ci","maxLength":1}],
    ["utf16", {"characterSet":"utf16","description":"UTF-16 Unicode","defaultCollation":"utf16_general_ci","maxLength":4}],
    ["utf16le", {"characterSet":"utf16le","description":"UTF-16LE Unicode","defaultCollation":"utf16le_general_ci","maxLength":4}],
    ["cp1256", {"characterSet":"cp1256","description":"Windows Arabic","defaultCollation":"cp1256_general_ci","maxLength":1}],
    ["cp1257", {"characterSet":"cp1257","description":"Windows Baltic","defaultCollation":"cp1257_general_ci","maxLength":1}],
    ["utf32", {"characterSet":"utf32","description":"UTF-32 Unicode","defaultCollation":"utf32_general_ci","maxLength":4}],
    ["binary", {"characterSet":"binary","description":"Binary pseudo charset","defaultCollation":"binary","maxLength":1}],
    ["geostd8", {"characterSet":"geostd8","description":"GEOSTD8 Georgian","defaultCollation":"geostd8_general_ci","maxLength":1}],
    ["cp932", {"characterSet":"cp932","description":"SJIS for Windows Japanese","defaultCollation":"cp932_japanese_ci","maxLength":2}],
    ["eucjpms", {"characterSet":"eucjpms","description":"UJIS for Windows Japanese","defaultCollation":"eucjpms_japanese_ci","maxLength":3}],
    ["gb18030", {"characterSet":"gb18030","description":"China National Standard GB18030","defaultCollation":"gb18030_chinese_ci","maxLength":4}]
]);
