export const syntaxKinds = [
    "SourceFile",

    "LeadingStatement",
    "TrailingStatement",
    "StatementTail",

    "Statement",
    "DelimiterStatement",
    "BinLogStatement",
    "CreateSchemaStatement",
    "CreateTableStatement",
    "SelectStatement",

    "Select",
    "ExpressionSelectItem",
    "SelectItemList1",

    "CreateTableDefinition",
    "CreateTableDefinitionTuple1",
    "CreateTableOption",
    "CreateTableOptionSemiList1",
    "Partition",

    "CreateSchemaOption",
    "CreateSchemaOptionRepeat1",
    "DefaultCharacterSet",
    "DefaultCollate",
    "CharacterSetNameOrDefault",
    "CollationNameOrDefault",
    "CharSet",
    "Schema",

    "ColumnDefinition",
    "IndexDefinition",
    "CheckDefinition",
    "PrimaryKeyDefinition",
    "ForeignKeyDefinition",


    "CreateTableOptionEngine",
    "CreateTableOptionMaxRows",
    "CreateTableOptionMinRows",
    "CreateTableOptionAverageRowLength",
    "CreateTableOptionPassword",
    "CreateTableOptionComment",
    "CreateTableOptionCompression",
    "CreateTableOptionEncryption",
    "CreateTableOptionAutoIncrement",
    "CreateTableOptionPackKeys",
    "CreateTableOptionStatsAutoRecalc",
    "CreateTableOptionStatsPersistent",
    "CreateTableOptionStatsSamplePages",
    "CreateTableOptionChecksum",
    "CreateTableOptionDelayKeyWrite",
    "CreateTableOptionRowFormat",
    "RowFormat",
    "CreateTableOptionUnion",
    "CreateTableOptionInsertMethod",
    "InsertMethod",
    "CreateTableOptionDataDirectory",
    "CreateTableOptionIndexDirectory",
    "CreateTableOptionTablespace",
    "CreateTableOptionStorage",
    "Storage",
    "CreateTableOptionConnection",
    "CreateTableOptionKeyBlockSize",

    "HashPartition",
    "KeyPartition",
    "ListPartition",
    "ListPartitionByExpression",
    "ListPartitionByColumn",
    "ListPartitionByColumnTuple2",
    "SingletonListPartitionDefinition",
    "SingletonListPartitionDefinitionTuple1",
    "MultitonListPartitionDefinition",
    "MultitonListPartitionDefinitionTuple1",
    "SingletonRangePartitionDefinition",
    "SingletonRangePartitionDefinitionTuple1",
    "RangePartition",

    "PartitionDefinitionOption",
    "PartitionDefinitionOptionRepeat1",

    "SubPartitionDefinition",
    "SubPartitionDefinitionTuple1",

    "PartitionDefinitionOptionEngine",
    "PartitionDefinitionOptionMaxRows",
    "PartitionDefinitionOptionMinRows",
    "PartitionDefinitionOptionComment",
    "PartitionDefinitionOptionDataDirectory",
    "PartitionDefinitionOptionIndexDirectory",
    "PartitionDefinitionOptionTablespace",
    "PartitionDefinitionOptionNodeGroup",

    "SubPartition",
    "HashSubPartition",
    "KeySubPartition",

    "Expression",
    "BooleanPrimaryExpression",
    "Predicate",

    "BitExpression",
    "BitwiseXor",
    "MulDivMod",
    "PlusMinus",
    "BitwiseShift",
    "BitwiseAnd",
    "BitwiseOr",

    "SimpleExpression",
    "BitExpressionTuple1",
    "BitExpressionTuple1Tuple1",

    "IfNotExists",
    "Ident",
    "IdentOrReserved",
    "TableIdentifier",

    "IdentTuple1",
    "IdentTuple2",
    "TableIdentifierTuple",
];
